/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connexion par matricule et mot de passe */
        post: operations["AuthController_connecter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/moi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identité et permissions de l'agent connecté */
        get: operations["AuthController_moi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mot-de-passe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Changement de mot de passe
         * @description Invalide tous les jetons de l'agent, y compris celui de l'appel : le jeton neuf renvoyé remplace le précédent.
         */
        post: operations["AuthController_changerMotDePasse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des comptes */
        get: operations["AgentsController_lister"];
        put?: never;
        /**
         * Création d'un compte
         * @description Il n'existe pas d'inscription libre. Le compte créé est en changement de mot de passe imposé.
         */
        post: operations["AgentsController_creer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fiche d'un compte */
        get: operations["AgentsController_lire"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modification d'un compte */
        patch: operations["AgentsController_modifier"];
        trace?: never;
    };
    "/agents/{id}/mot-de-passe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Réinitialisation du mot de passe
         * @description Renvoie un mot de passe provisoire affiché une seule fois, révoque les jetons et repasse le compte en changement imposé.
         */
        post: operations["AgentsController_reinitialiserMotDePasse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/anonymiser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Anonymisation — seule forme de retrait d'un compte
         * @description Efface les données personnelles, conserve l'enregistrement et ses références, révoque les jetons. Irréversible.
         */
        post: operations["AgentsController_anonymiser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Grades et leurs permissions
         * @description Lisible par tout agent connecté : savoir ce qu'un grade autorise ne révèle rien sur les données.
         */
        get: operations["RolesController_lister"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/catalogue-permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogue des permissions attribuables */
        get: operations["RolesController_catalogue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Configuration d'un grade */
        patch: operations["RolesController_modifier"];
        trace?: never;
    };
    "/referentiel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogue complet en une requête */
        get: operations["ReferentielController_catalogue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referentiel/types-entites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Création d'un type d'entité */
        post: operations["ReferentielController_creerTypeEntite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referentiel/types-entites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Suppression d'un type d'entité
         * @description Refusée dès qu'une entité de ce type existe : le référentiel ne se vide pas sous les données qui en dépendent.
         */
        delete: operations["ReferentielController_supprimerTypeEntite"];
        options?: never;
        head?: never;
        patch: operations["ReferentielController_modifierTypeEntite"];
        trace?: never;
    };
    "/referentiel/types-entites/ordre": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ordre d'affichage des types d'entités */
        post: operations["ReferentielController_ordonnerTypesEntites"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referentiel/types-entites/apercu-gabarit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aperçu d'un gabarit de libellé
         * @description Vérifie sa forme et montre ce qu'il produirait.
         */
        post: operations["ReferentielController_apercuGabarit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referentiel/champs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReferentielController_creerChamp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referentiel/champs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ReferentielController_supprimerChamp"];
        options?: never;
        head?: never;
        patch: operations["ReferentielController_modifierChamp"];
        trace?: never;
    };
    "/referentiel/types-entites/{id}/champs/ordre": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReferentielController_ordonnerChamps"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referentiel/types-liens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Création d'un type de lien
         * @description Ses contraintes de domaine sont définitives : des liens déjà posés les respectent.
         */
        post: operations["ReferentielController_creerTypeLien"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referentiel/types-liens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ReferentielController_supprimerTypeLien"];
        options?: never;
        head?: never;
        patch: operations["ReferentielController_modifierTypeLien"];
        trace?: never;
    };
    "/referentiel/onglets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReferentielController_creerOnglet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referentiel/onglets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ReferentielController_supprimerOnglet"];
        options?: never;
        head?: never;
        patch: operations["ReferentielController_modifierOnglet"];
        trace?: never;
    };
    "/referentiel/types-entites/{id}/onglets/ordre": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReferentielController_ordonnerOnglets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referentiel/onglets/{id}/types-liens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Composition d'un onglet
         * @description Jeu complet, dans l'ordre. Le sens doit placer le type d'entité de l'onglet du bon côté du lien.
         */
        put: operations["ReferentielController_composerOnglet"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Annuaire filtrable */
        get: operations["EntitesController_lister"];
        put?: never;
        /**
         * Création d’une entité et de ses premiers faits
         * @description Source, fiabilité et date de constatation données au niveau de la requête servent de valeurs par défaut à chaque fait — c’est le bandeau de source active.
         */
        post: operations["EntitesController_creer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entites/similaires": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Détection de doublons à la frappe
         * @description Similarité trigramme du libellé, et identité exacte d’une valeur unique du type — ce second signal ne laisse aucun doute.
         */
        get: operations["EntitesController_similaires"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fiche assemblée
         * @description Champs projetés avec les faits qui les soutiennent, et liens lus depuis cette fiche — un lien est une arête unique, vue des deux côtés.
         */
        get: operations["EntitesController_lire"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["EntitesController_modifier"];
        trace?: never;
    };
    "/entites/{id}/archiver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archivage
         * @description Rien n’est jamais supprimé : l’entité sort des écrans courants et reste consultable, ses faits intacts.
         */
        post: operations["EntitesController_archiver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entites/{id}/desarchiver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EntitesController_desarchiver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/faits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ajout d’un fait à une entité existante
         * @description Un lien créé ici est lisible depuis ses deux extrémités : une seule arête est stockée.
         */
        post: operations["FaitsController_creer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/faits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Correction d’un fait
         * @description La cible d’un lien ne se corrige pas : un lien mal posé s’infirme et se refait.
         */
        patch: operations["FaitsController_modifier"];
        trace?: never;
    };
    "/sante": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** État de l'API et de sa base */
        get: operations["SanteController_lire"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ConnexionDto: {
            /** @example 2291 */
            matricule: string;
            motDePasse: string;
        };
        AgentConnecteDto: {
            id: string;
            matricule: string;
            prenom: string;
            nom: string;
            roleCode: string;
            superAdmin: boolean;
            /** @description Tant qu'il vaut true, seules /auth/moi et /auth/mot-de-passe répondent */
            doitChangerMdp: boolean;
            /** @description Codes de permissions du grade. Un super-admin contourne ce jeu. */
            permissions: string[];
        };
        JetonDto: {
            /** @description À placer en en-tête Authorization: Bearer … */
            jeton: string;
            agent: components["schemas"]["AgentConnecteDto"];
        };
        ChangementMotDePasseDto: {
            ancien: string;
            nouveau: string;
        };
        AgentDto: {
            /** Format: uuid */
            id: string;
            /** @description Valeur technique dérivée de l'id chez un compte anonymisé */
            matricule: string;
            /** @description Vide chez un compte anonymisé */
            prenom: string;
            /** @description Vide chez un compte anonymisé */
            nom: string;
            /** @description Prêt à l'affichage — « agent supprimé » si anonymisé */
            libelle: string;
            /** Format: uuid */
            roleId: string;
            roleCode: string;
            roleLibelle: string;
            superAdmin: boolean;
            actif: boolean;
            doitChangerMdp: boolean;
            anonymise: boolean;
            /** Format: date-time */
            anonymiseLe: string | null;
            /** Format: date-time */
            creeLe: string;
        };
        CreationAgentDto: {
            /** @example 2291 */
            matricule: string;
            /** @example Isadora */
            prenom: string;
            /** @example Morales */
            nom: string;
            /** Format: uuid */
            roleId: string;
            /**
             * @description Attribut du compte, indépendant du grade RP
             * @default false
             */
            superAdmin: boolean;
            /** @description Laisser vide pour qu'un mot de passe provisoire soit engendré et renvoyé une seule fois */
            motDePasse?: string;
        };
        AgentAvecMotDePasseDto: {
            agent: components["schemas"]["AgentDto"];
            /** @description Mot de passe provisoire, affiché une seule fois. Le compte est en changement imposé. */
            motDePasseProvisoire: string | null;
        };
        ModificationAgentDto: {
            prenom?: string;
            nom?: string;
            /** Format: uuid */
            roleId?: string;
            actif?: boolean;
            superAdmin?: boolean;
        };
        RoleDto: {
            /** Format: uuid */
            id: string;
            /** @example senior_investigator */
            code: string;
            /** @example Senior Investigator */
            libelle: string;
            permissions: string[];
            ordre: number;
        };
        PermissionCatalogueeDto: {
            /** @example entite.archiver */
            code: string;
            /** @example Archiver une entité */
            libelle: string;
        };
        ModificationRoleDto: {
            libelle?: string;
            /** @description Jeu complet, il remplace le précédent */
            permissions?: string[];
        };
        DefinitionChampDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            typeEntiteId: string;
            /** @example plaque */
            cle: string;
            /** @example Plaque */
            libelle: string;
            /** @enum {string} */
            typeDonnee: "texte" | "nombre" | "date" | "datetime" | "booleen" | "liste" | "fichier";
            obligatoire: boolean;
            estUnique: boolean;
            multiple: boolean;
            /** @description Valeurs autorisées, pour une liste fermée uniquement */
            options: string[] | null;
            ordre: number;
        };
        OngletTypeLienDto: {
            /** Format: uuid */
            typeLienId: string;
            /**
             * @description « inverse » affiche le lien vu de l'autre extrémité : l'onglet Membres du groupe montre le côté inverse de « membre de »
             * @enum {string}
             */
            sens: "direct" | "inverse";
            ordre: number;
        };
        OngletDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            typeEntiteId: string;
            /** @example Membres */
            libelle: string;
            ordre: number;
            typesLiens: components["schemas"]["OngletTypeLienDto"][];
        };
        TypeEntiteDto: {
            /** Format: uuid */
            id: string;
            /** @example vehicule */
            code: string;
            /** @example Véhicule */
            libelle: string;
            /** @example Véhicules */
            libellePluriel: string;
            /** @example car */
            icone: string;
            /** @example {plaque} */
            modeleLibelle: string;
            ordre: number;
            champs: components["schemas"]["DefinitionChampDto"][];
            onglets: components["schemas"]["OngletDto"][];
        };
        TypeLienDto: {
            /** Format: uuid */
            id: string;
            /** @example proprietaire_de */
            code: string;
            /** @example propriétaire de */
            libelle: string;
            /** @example appartient à */
            libelleInverse: string;
            /** Format: uuid */
            typeEntiteSourceId: string;
            /** Format: uuid */
            typeEntiteCibleId: string;
            multiple: boolean;
            ordre: number;
        };
        ReferentielDto: {
            typesEntites: components["schemas"]["TypeEntiteDto"][];
            typesLiens: components["schemas"]["TypeLienDto"][];
        };
        CreationTypeEntiteDto: {
            /** @example vehicule */
            code: string;
            /** @example Véhicule */
            libelle: string;
            /** @example Véhicules */
            libellePluriel: string;
            /**
             * @description Nom d'icône du design system
             * @example car
             */
            icone: string;
            /**
             * @description Gabarit de libellé, citant des clés de champs entre accolades
             * @example {plaque}
             */
            modeleLibelle: string;
        };
        ModificationTypeEntiteDto: {
            libelle?: string;
            libellePluriel?: string;
            icone?: string;
            modeleLibelle?: string;
        };
        OrdreDto: {
            /** @description Identifiants dans l'ordre voulu. Le jeu doit être complet. */
            ids: string[];
        };
        ApercuGabaritDto: {
            /** @example {prenom} {nom} */
            modeleLibelle: string;
        };
        ResultatApercuDto: {
            /** @example Tyron Banks */
            apercu: string;
            clesCitees: string[];
        };
        CreationChampDto: {
            /** Format: uuid */
            typeEntiteId: string;
            /** @example plaque */
            cle: string;
            /** @example Plaque */
            libelle: string;
            /** @enum {string} */
            typeDonnee: "texte" | "nombre" | "date" | "datetime" | "booleen" | "liste" | "fichier";
            /** @default false */
            obligatoire: boolean;
            /** @default false */
            estUnique: boolean;
            /** @default false */
            multiple: boolean;
            /** @description Obligatoire et réservé au type « liste » */
            options?: string[];
        };
        ModificationChampDto: {
            libelle?: string;
            obligatoire?: boolean;
            estUnique?: boolean;
            multiple?: boolean;
            options?: string[];
        };
        CreationTypeLienDto: {
            /** @example proprietaire_de */
            code: string;
            /** @example propriétaire de */
            libelle: string;
            /**
             * @description Le même lien, lu depuis la cible
             * @example appartient à
             */
            libelleInverse: string;
            /** Format: uuid */
            typeEntiteSourceId: string;
            /** Format: uuid */
            typeEntiteCibleId: string;
            /** @default true */
            multiple: boolean;
        };
        ModificationTypeLienDto: {
            libelle?: string;
            libelleInverse?: string;
            multiple?: boolean;
        };
        CreationOngletDto: {
            /** Format: uuid */
            typeEntiteId: string;
            /** @example Membres */
            libelle: string;
        };
        ModificationOngletDto: {
            libelle?: string;
        };
        LienDOngletDto: {
            /** Format: uuid */
            typeLienId: string;
            /** @enum {string} */
            sens: "direct" | "inverse";
        };
        CompositionOngletDto: {
            /** @description Jeu complet, dans l'ordre voulu. Il remplace le précédent. */
            typesLiens: components["schemas"]["LienDOngletDto"][];
        };
        EntiteResumeeDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            typeEntiteId: string;
            typeCode: string;
            libelle: string;
            /** @enum {string} */
            visibilite: "public" | "restreint" | "prive";
            /** @enum {string} */
            etat: "actif" | "archive";
            /** Format: date-time */
            modifieLe: string;
        };
        SuggestionDoublonDto: {
            /** Format: uuid */
            id: string;
            libelle: string;
            typeCode: string;
            /** @description Similarité trigramme du libellé, entre 0 et 1 */
            proximite: number;
            /** @description Une valeur unique du type est identique — c’est un doublon sûr */
            valeurUniqueIdentique: boolean;
        };
        FaitDeChampDto: {
            /** Format: uuid */
            id: string;
            valeur: Record<string, never>;
            source: string;
            fiabilite: number;
            /** Format: date */
            dateConstatation: string;
            /** @enum {string} */
            visibilite: "public" | "restreint" | "prive";
        };
        ChampDeFicheDto: {
            /** Format: uuid */
            definitionChampId: string;
            cle: string;
            libelle: string;
            /** @enum {string} */
            typeDonnee: "texte" | "nombre" | "date" | "datetime" | "booleen" | "liste" | "fichier";
            multiple: boolean;
            /** @description Valeur projetée, celle qui s’affiche en évidence */
            valeur: Record<string, never>;
            /** @description Les faits qui la soutiennent. Plus d’un signale un recoupement de sources. */
            faits: components["schemas"]["FaitDeChampDto"][];
            /** @description Plusieurs sources distinctes affirment la même valeur */
            multiSources: boolean;
        };
        ExtremiteDto: {
            /** Format: uuid */
            id: string;
            libelle: string;
            typeCode: string;
        };
        LienDeFicheDto: {
            /**
             * Format: uuid
             * @description Identifiant du fait
             */
            faitId: string;
            /**
             * @description Le même fait, vu depuis l’une ou l’autre extrémité. Une seule arête existe en base.
             * @enum {string}
             */
            sens: "direct" | "inverse";
            /** Format: uuid */
            typeLienId: string;
            /** @description Libellé lu depuis cette fiche */
            libelle: string;
            autreEntite: components["schemas"]["ExtremiteDto"];
            source: string;
            fiabilite: number;
            /** Format: date */
            dateConstatation: string;
            /** @enum {string} */
            visibilite: "public" | "restreint" | "prive";
        };
        FicheEntiteDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            typeEntiteId: string;
            typeCode: string;
            libelle: string;
            /** @enum {string} */
            visibilite: "public" | "restreint" | "prive";
            /** @enum {string} */
            etat: "actif" | "archive";
            /** Format: date-time */
            modifieLe: string;
            typeLibelle: string;
            /** @description Projection des faits, maintenue par trigger */
            valeurs: {
                [key: string]: unknown;
            };
            note: string | null;
            champs: components["schemas"]["ChampDeFicheDto"][];
            liens: components["schemas"]["LienDeFicheDto"][];
            /** Format: date-time */
            creeLe: string;
            /** Format: uuid */
            fusionneeVersId: string | null;
        };
        ChampSaisiDto: {
            /** @example Rapport d'intervention n°2291 */
            source?: string;
            fiabilite?: number;
            /**
             * Format: date
             * @example 2026-08-07
             */
            dateConstatation?: string;
            /** @enum {string} */
            visibilite?: "public" | "restreint" | "prive";
            /** Format: uuid */
            definitionChampId: string;
            /** @description Texte, nombre, booléen ou valeur de liste, selon le type du champ */
            valeur: Record<string, never>;
        };
        LienSaisiDto: {
            /** @example Rapport d'intervention n°2291 */
            source?: string;
            fiabilite?: number;
            /**
             * Format: date
             * @example 2026-08-07
             */
            dateConstatation?: string;
            /** @enum {string} */
            visibilite?: "public" | "restreint" | "prive";
            /** Format: uuid */
            typeLienId: string;
            /** Format: uuid */
            cibleId: string;
        };
        CreationEntiteDto: {
            /** @example Rapport d'intervention n°2291 */
            source?: string;
            fiabilite?: number;
            /**
             * Format: date
             * @example 2026-08-07
             */
            dateConstatation?: string;
            /** @enum {string} */
            visibilite?: "public" | "restreint" | "prive";
            /** Format: uuid */
            typeEntiteId: string;
            /** @description Champ libre, sans source ni fiabilité — ce n’est pas un fait */
            note?: string;
            champs?: components["schemas"]["ChampSaisiDto"][];
            liens?: components["schemas"]["LienSaisiDto"][];
        };
        ModificationEntiteDto: {
            note?: string;
            /**
             * @description Exige la permission visibilite.definir
             * @enum {string}
             */
            visibilite?: "public" | "restreint" | "prive";
        };
        CreationFaitDto: {
            /** Format: uuid */
            sujetId: string;
            /** @enum {string} */
            nature: "champ" | "lien";
            /**
             * Format: uuid
             * @description Si nature = champ
             */
            definitionChampId?: string;
            /** @description Si nature = champ */
            valeur?: Record<string, never>;
            /**
             * Format: uuid
             * @description Si nature = lien
             */
            typeLienId?: string;
            /**
             * Format: uuid
             * @description Si nature = lien
             */
            cibleId?: string;
            /** @example Rapport d'intervention n°2291 */
            source: string;
            fiabilite: number;
            /**
             * Format: date
             * @example 2026-08-07
             */
            dateConstatation: string;
            /** @enum {string} */
            visibilite?: "public" | "restreint" | "prive";
        };
        FaitDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sujetId: string;
            /** @enum {string} */
            nature: "champ" | "lien";
            /** Format: uuid */
            definitionChampId: string | null;
            valeur: Record<string, never> | null;
            /** Format: uuid */
            typeLienId: string | null;
            /** Format: uuid */
            cibleId: string | null;
            source: string;
            fiabilite: number;
            /** Format: date */
            dateConstatation: string;
            /** @enum {string} */
            etat: "actif" | "infirme" | "archive";
            /** @enum {string} */
            visibilite: "public" | "restreint" | "prive";
            /** Format: date-time */
            creeLe: string;
            /** Format: date-time */
            modifieLe: string;
        };
        ModificationFaitDto: {
            /** @description Champ seulement — la cible d’un lien ne se corrige pas */
            valeur?: Record<string, never>;
            source?: string;
            fiabilite?: number;
            /** Format: date */
            dateConstatation?: string;
            /** @enum {string} */
            visibilite?: "public" | "restreint" | "prive";
        };
        SanteReponseDto: {
            /**
             * @description « degrade » dès que la base ne répond pas
             * @enum {string}
             */
            etat: "operationnel" | "degrade";
            /** @description Version du paquet applicatif */
            version: string;
            /** @description La base PostgreSQL répond */
            base: boolean;
            /** @description Secondes écoulées depuis le démarrage */
            demarre_depuis: number;
            /** Format: date-time */
            horodatage: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_connecter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnexionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JetonDto"];
                };
            };
            /** @description Identifiants invalides */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_moi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConnecteDto"];
                };
            };
        };
    };
    AuthController_changerMotDePasse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangementMotDePasseDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JetonDto"];
                };
            };
        };
    };
    AgentsController_lister: {
        parameters: {
            query?: {
                /** @description Inclure les comptes anonymisés */
                anonymises?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDto"][];
                };
            };
        };
    };
    AgentsController_creer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreationAgentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentAvecMotDePasseDto"];
                };
            };
            /** @description Matricule déjà attribué */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AgentsController_lire: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDto"];
                };
            };
        };
    };
    AgentsController_modifier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModificationAgentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDto"];
                };
            };
        };
    };
    AgentsController_reinitialiserMotDePasse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentAvecMotDePasseDto"];
                };
            };
        };
    };
    AgentsController_anonymiser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDto"];
                };
            };
            /** @description Déjà anonymisé, ou dernier super-admin */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_lister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"][];
                };
            };
        };
    };
    RolesController_catalogue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionCatalogueeDto"][];
                };
            };
        };
    };
    RolesController_modifier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModificationRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"];
                };
            };
        };
    };
    ReferentielController_catalogue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferentielDto"];
                };
            };
        };
    };
    ReferentielController_creerTypeEntite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreationTypeEntiteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeEntiteDto"];
                };
            };
        };
    };
    ReferentielController_supprimerTypeEntite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Type encore utilisé */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReferentielController_modifierTypeEntite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModificationTypeEntiteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeEntiteDto"];
                };
            };
        };
    };
    ReferentielController_ordonnerTypesEntites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrdreDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReferentielController_apercuGabarit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApercuGabaritDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultatApercuDto"];
                };
            };
        };
    };
    ReferentielController_creerChamp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreationChampDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefinitionChampDto"];
                };
            };
        };
    };
    ReferentielController_supprimerChamp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReferentielController_modifierChamp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModificationChampDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefinitionChampDto"];
                };
            };
        };
    };
    ReferentielController_ordonnerChamps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrdreDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReferentielController_creerTypeLien: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreationTypeLienDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeLienDto"];
                };
            };
        };
    };
    ReferentielController_supprimerTypeLien: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReferentielController_modifierTypeLien: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModificationTypeLienDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeLienDto"];
                };
            };
        };
    };
    ReferentielController_creerOnglet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreationOngletDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OngletDto"];
                };
            };
        };
    };
    ReferentielController_supprimerOnglet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReferentielController_modifierOnglet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModificationOngletDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OngletDto"];
                };
            };
        };
    };
    ReferentielController_ordonnerOnglets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrdreDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReferentielController_composerOnglet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompositionOngletDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OngletDto"];
                };
            };
            /** @description Sens incohérent avec le domaine du lien */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EntitesController_lister: {
        parameters: {
            query?: {
                type?: string;
                q?: string;
                etat?: "actif" | "archive";
                decalage?: unknown;
                limite?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntiteResumeeDto"][];
                };
            };
        };
    };
    EntitesController_creer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreationEntiteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FicheEntiteDto"];
                };
            };
            /** @description Valeur unique déjà attribuée */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EntitesController_similaires: {
        parameters: {
            query: {
                q: string;
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionDoublonDto"][];
                };
            };
        };
    };
    EntitesController_lire: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FicheEntiteDto"];
                };
            };
        };
    };
    EntitesController_modifier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModificationEntiteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FicheEntiteDto"];
                };
            };
        };
    };
    EntitesController_archiver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FicheEntiteDto"];
                };
            };
        };
    };
    EntitesController_desarchiver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FicheEntiteDto"];
                };
            };
        };
    };
    FaitsController_creer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreationFaitDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaitDto"];
                };
            };
        };
    };
    FaitsController_modifier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModificationFaitDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaitDto"];
                };
            };
        };
    };
    SanteController_lire: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SanteReponseDto"];
                };
            };
            /** @description Base injoignable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SanteReponseDto"];
                };
            };
        };
    };
}
