/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connexion par matricule et mot de passe */
        post: operations["AuthController_connecter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/moi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identité et permissions de l'agent connecté */
        get: operations["AuthController_moi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mot-de-passe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Changement de mot de passe
         * @description Invalide tous les jetons de l'agent, y compris celui de l'appel : le jeton neuf renvoyé remplace le précédent.
         */
        post: operations["AuthController_changerMotDePasse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des comptes */
        get: operations["AgentsController_lister"];
        put?: never;
        /**
         * Création d'un compte
         * @description Il n'existe pas d'inscription libre. Le compte créé est en changement de mot de passe imposé.
         */
        post: operations["AgentsController_creer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fiche d'un compte */
        get: operations["AgentsController_lire"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modification d'un compte */
        patch: operations["AgentsController_modifier"];
        trace?: never;
    };
    "/agents/{id}/mot-de-passe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Réinitialisation du mot de passe
         * @description Renvoie un mot de passe provisoire affiché une seule fois, révoque les jetons et repasse le compte en changement imposé.
         */
        post: operations["AgentsController_reinitialiserMotDePasse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/anonymiser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Anonymisation — seule forme de retrait d'un compte
         * @description Efface les données personnelles, conserve l'enregistrement et ses références, révoque les jetons. Irréversible.
         */
        post: operations["AgentsController_anonymiser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Grades et leurs permissions
         * @description Lisible par tout agent connecté : savoir ce qu'un grade autorise ne révèle rien sur les données.
         */
        get: operations["RolesController_lister"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/catalogue-permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogue des permissions attribuables */
        get: operations["RolesController_catalogue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Configuration d'un grade */
        patch: operations["RolesController_modifier"];
        trace?: never;
    };
    "/sante": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** État de l'API et de sa base */
        get: operations["SanteController_lire"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ConnexionDto: {
            /** @example 2291 */
            matricule: string;
            motDePasse: string;
        };
        AgentConnecteDto: {
            id: string;
            matricule: string;
            prenom: string;
            nom: string;
            roleCode: string;
            superAdmin: boolean;
            /** @description Tant qu'il vaut true, seules /auth/moi et /auth/mot-de-passe répondent */
            doitChangerMdp: boolean;
            /** @description Codes de permissions du grade. Un super-admin contourne ce jeu. */
            permissions: string[];
        };
        JetonDto: {
            /** @description À placer en en-tête Authorization: Bearer … */
            jeton: string;
            agent: components["schemas"]["AgentConnecteDto"];
        };
        ChangementMotDePasseDto: {
            ancien: string;
            nouveau: string;
        };
        AgentDto: {
            /** Format: uuid */
            id: string;
            /** @description Valeur technique dérivée de l'id chez un compte anonymisé */
            matricule: string;
            /** @description Vide chez un compte anonymisé */
            prenom: string;
            /** @description Vide chez un compte anonymisé */
            nom: string;
            /** @description Prêt à l'affichage — « agent supprimé » si anonymisé */
            libelle: string;
            /** Format: uuid */
            roleId: string;
            roleCode: string;
            roleLibelle: string;
            superAdmin: boolean;
            actif: boolean;
            doitChangerMdp: boolean;
            anonymise: boolean;
            /** Format: date-time */
            anonymiseLe: string | null;
            /** Format: date-time */
            creeLe: string;
        };
        CreationAgentDto: {
            /** @example 2291 */
            matricule: string;
            /** @example Isadora */
            prenom: string;
            /** @example Morales */
            nom: string;
            /** Format: uuid */
            roleId: string;
            /**
             * @description Attribut du compte, indépendant du grade RP
             * @default false
             */
            superAdmin: boolean;
            /** @description Laisser vide pour qu'un mot de passe provisoire soit engendré et renvoyé une seule fois */
            motDePasse?: string;
        };
        AgentAvecMotDePasseDto: {
            agent: components["schemas"]["AgentDto"];
            /** @description Mot de passe provisoire, affiché une seule fois. Le compte est en changement imposé. */
            motDePasseProvisoire: string | null;
        };
        ModificationAgentDto: {
            prenom?: string;
            nom?: string;
            /** Format: uuid */
            roleId?: string;
            actif?: boolean;
            superAdmin?: boolean;
        };
        RoleDto: {
            /** Format: uuid */
            id: string;
            /** @example senior_investigator */
            code: string;
            /** @example Senior Investigator */
            libelle: string;
            permissions: string[];
            ordre: number;
        };
        PermissionCatalogueeDto: {
            /** @example entite.archiver */
            code: string;
            /** @example Archiver une entité */
            libelle: string;
        };
        ModificationRoleDto: {
            libelle?: string;
            /** @description Jeu complet, il remplace le précédent */
            permissions?: string[];
        };
        SanteReponseDto: {
            /**
             * @description « degrade » dès que la base ne répond pas
             * @enum {string}
             */
            etat: "operationnel" | "degrade";
            /** @description Version du paquet applicatif */
            version: string;
            /** @description La base PostgreSQL répond */
            base: boolean;
            /** @description Secondes écoulées depuis le démarrage */
            demarre_depuis: number;
            /** Format: date-time */
            horodatage: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_connecter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnexionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JetonDto"];
                };
            };
            /** @description Identifiants invalides */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_moi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConnecteDto"];
                };
            };
        };
    };
    AuthController_changerMotDePasse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangementMotDePasseDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JetonDto"];
                };
            };
        };
    };
    AgentsController_lister: {
        parameters: {
            query?: {
                /** @description Inclure les comptes anonymisés */
                anonymises?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDto"][];
                };
            };
        };
    };
    AgentsController_creer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreationAgentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentAvecMotDePasseDto"];
                };
            };
            /** @description Matricule déjà attribué */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AgentsController_lire: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDto"];
                };
            };
        };
    };
    AgentsController_modifier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModificationAgentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDto"];
                };
            };
        };
    };
    AgentsController_reinitialiserMotDePasse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentAvecMotDePasseDto"];
                };
            };
        };
    };
    AgentsController_anonymiser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDto"];
                };
            };
            /** @description Déjà anonymisé, ou dernier super-admin */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_lister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"][];
                };
            };
        };
    };
    RolesController_catalogue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionCatalogueeDto"][];
                };
            };
        };
    };
    RolesController_modifier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModificationRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDto"];
                };
            };
        };
    };
    SanteController_lire: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SanteReponseDto"];
                };
            };
            /** @description Base injoignable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SanteReponseDto"];
                };
            };
        };
    };
}
